#!/bin/bash
set -ue

set_up() {
    return 0
}

was_run() {
    local test_name="$1"
    eval "${test_name}_WAS_RUN=true"
    return 0
}

tear_down() {
    return 0
}

set_up_test() {
    local test_name="$1"
    eval "${test_name}_WAS_RUN=false"
    set_up
    eval "${test_name}_WAS_SET_UP=true"
    return 0
}

tear_down_test() {
    local test_name="$1"
    tear_down
    eval "${test_name}_TEAR_DOWN=true"
    return 0
}

log_status() {
    local test_name="$1"
    local status="$2"
    if [[ "$status" == "0" ]]; then
        echo "OK: $test_name"
    else
        echo "FAILED: $test_name"
    fi
}

run() {
    local test_method="$1"
    shift
    local args=($@)
    set_up_test "$test_method"
    $test_method "${args[@]}"
    local status="$?"
    log_status "$test_method" "$status"
    was_run "$test_method"
    tear_down_test "${test_method}"
    return "$status"
}