#!/bin/bash
set -ue

export SH_UNIT_DIR="$PWD"

set_up() {
    return 0
}

was_run() {
    local test_name="$1"
    eval "${test_name}_WAS_RUN=true"
    return 0
}

tear_down() {
    return 0
}

set_up_test() {
    local test_name="$1"
    eval "${test_name}_WAS_RUN=false"
    set_up
    eval "${test_name}_WAS_SET_UP=true"
    return 0
}

tear_down_test() {
    local test_name="$1"
    tear_down
    eval "${test_name}_TEAR_DOWN=true"
    return 0
}

log_status() {
    local test_name="$1"
    local status="$2"
    if [[ "$status" == "0" ]]; then
        echo "OK: $test_name"
    else
        echo "FAILED: $test_name"
    fi
}

run() {
    local test_name="$1"
    echo "$test_name - name"
    set_up_test "$test_name"
    echo "$test_name - 2name"
    "$test_name"
    local status="$?"
    echo "$test_name - 3name"
    was_run "$test_name"
    log_status "$test_name" "$status"
    tear_down_test "${test_name}"
    return "$status"
}

execute_suite() {
    local suite_filename="$1"
    local test_list
    IFS=$'\n' test_list=($(grep -Po "test_\w+(?=\(\))" "$suite_filename"))
    echo "$suite_filename"
    echo "${test_list[@]}"
    source "$suite_filename"
    for test_name in "${test_list[@]}"; do
        echo "$test_name"
        run "$test_name" || return 1
    done
    return 0
}
