#!/bin/bash

#shellcheck source=shUnit
source "./shUnit"
source "./test"


test_method() {
    method
    return 0
}

test_another_method() {
    another_method
    return 0
}

test_run() {
    local test_name=test_method
    local was_run_var="${test_name}_WAS_RUN"
    run test_method
    if ! "${!was_run_var}"; then
        return 1
    fi
    return 0
}

test_set_up_test() {
    local test_name=test_method
    local set_up_var="${test_name}_WAS_SET_UP"
    set_up_test "$test_name"
    if ! "${!set_up_var}"; then
        return 1
    fi
    return 0
}

test_was_run() {
    local test_name=test_method
    local was_run_var="${test_name}_WAS_RUN"
    if "${!was_run_var}"; then
        return 1
    fi
    was_run "$test_name"
    if ! "${!was_run_var}"; then
        return 1
    fi
    return 0
}

test_tear_down_test() {
    local test_name=test_method
    local tear_down_var="${test_name}_WAS_TEAR_DOWN"
    tear_down_test "$test_name"
    if ! "${!tear_down_var}"; then
        return 1
    fi
    return 0
}

test_log_status() {
    local ok_message
    ok_message="$(log_status my_test 0)"
    local failed_message
    failed_message="$(log_status my_test 1)"
    if [[ "$ok_message" == "OK: my_test" && "$failed_message" == "FAILED: my_test" ]]; then
        return 0
    fi
    return 1
}

check_ran_tests() {
    local test_filename="$1"
    local test_list
    local test_name
    IFS=$'\n' read -r -d '' -a test_list <<<"$(grep -Po "test_\w+(?=\(\))" "$test_filename")"
    for test_name in "${test_list[@]}"; do
        local test_was_run="${test_name}_WAS_RUN"
        if ! "${!test_was_run}"; then
            return 1
        fi
    done
    return 0
}

test_execute_suite() {
    local suite_filename="./test_test"
    execute_suite "$suite_filename"
    check_ran_tests "$suite_filename"
}

test_execute_tests() {
    local test_file="./test_test"
    execute_tests "$test_file" "./shUnit"
    check_ran_tests "$test_file"
}

test_find_testnames() {
    local 
}

run test_tear_down_test
run test_another_method
run test_set_up_test
run test_was_run
run test_run
run test_method
run test_log_status
run test_execute_suite
run test_execute_tests
